### ISSUE TITLE
Le simulateur disparait lorsque la valeur "500" est utilisée

### ISSUE THREAD

**Issue by thombet** [betagouv/ecolab-transport#112]
Bonjour,

Je voudrais signaler un bug assez bizarre : lorsque j'entre la valeur 500 dans le nombre de kilomètres du [simulateur](https://ecolab.ademe.fr/apps/transport), le simulateur disparait (c'est-à-dire on ne voit plus qu'une page blanche).
De manière assez surprenante ça ne le fait pas avec 5, 50, 501, 502, 400, 600, 499, etc.

J'ai pu reproduire le problème sur iOS (Firefox et Safari) et sur MacOS (Firefox et Safari).
Est-ce que vous avez le même comportement de votre côté ?

Merci d'avance.

**Comment by laem** [comment]
Merci :)
