### ISSUE TITLE
Matomo semble déconnecté depuis le changement de nom de domaine

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-transport#125]

**Comment by martinregner** [comment]
@florianpanchout tu avais pu regarder vendredi ? Cela ne semble toujours pas fonctionner :(

**Comment by florianpanchout** [comment]
Je ne vois pas d'ou peut venir le problème. 

@laem Est ce qu'il n'y aurait pas une mauvaise url spécifiée quelque part dans Matomo ? (https://ecolab.ademe.fr/apps/transport à la place de http://monimpacttransport.fr/)
