### ISSUE TITLE
En intégrant l'iframe, pouvoir initialiser l'onglet affiché et le kilométrage

### ISSUE THREAD

**Issue by fjg** [betagouv/ecolab-transport#22]
Ca permet de faire un article ou contextualiser sur une situation (ex: impact carbone d'un Paris-Dijon cf. PSG https://www.ouest-france.fr/sport/football/paris-sg/commentaire-psg-l-avion-de-la-honte-6736936 ;)

Petit calcul des émissions en utilisant flightradar24 et le simulateur ecolab :

- Aller : https://www.flightradar24.com/data/aircraft/9h-aha/#23d7c7a3 (271km)
- Retour https://www.flightradar24.com/data/aircraft/9h-aha/#23d63c35 (273km)
=> 221 kg de CO2e

- Bus : 348km*2 dit l'article soit 41kg

Soit en tout 261kg CO2e

Exemple : **https://ecolab-transport.netlify.com/?distance=544&zone=france** (zone=local/work/france/europe/world, distance en km)

ou en data attributes **data-distance** et **data-zone**

```
<script
id="ecolab-transport" data-couleur="purple" data-distance="544" data-zone="france" src="https://ecolab-transport.netlify.com/iframe.js"></script>
```

**Comment by laem** [comment]
Oups, je l'ai fait pour la distance mais j'ai pas mis à jour la doc : https://ecolab-transport.netlify.com/?distanceInitiale=89
Je suis moins sûr pour la "zone", j'ai l'impression que la distance suffit dans un 1er temps

**Comment by fjg** [comment]
Effectivement, ca affiche les bons éléments en fonction de la distance. Donc ca fait ce pourquoi je l'imaginais.
Les params c'est pas en anglais comme le code ?

Je clos du coup.

**Comment by laem** [comment]
Je me dis que c'est pas forcément des dev qui vont tomber sur cette documentation, et que ce module restera exclusif à la France pendant un moment, donc plutôt français. 
J'ai poussé la documentation manquante ✅
