### ISSUE TITLE
Integrate iframe on localhost website

### ISSUE THREAD

**Issue by fjg** [betagouv/ecolab-transport#39]
When we integrate the iframe on a (localhost) website, cause of https://github.com/betagouv/ecolab-transport/blob/master/iframe.js#L11, it redirects to localhost:8080 which is not listening & responding.

**Comment by laem** [comment]
Yes, we should probably make iframe.js always listen to the netlify URL, and up to the developer to change it to the local adress of ecolab-transport when working on the iframe integration
