### ISSUE TITLE
Suivi utilisation de l'iframe

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-transport#54]
Serait-il possible de connaître :
- les sites / pages qui l'utilisent ?
- le nombre de calculs (changement de valeur de km ?) fait ?

**Comment by laem** [comment]
Yep, il faut qu'on intègre Matomo, stats.data.gouv.fr, comme on l'a fait sur mon-entreprise

**Comment by laem** [comment]
Pour l'instant je tente une approche naïve : j'intègre simplement ecolab et ecolab-transport sur le même site Matomo. On verra au bout de quelques jours ce que ça donne. 
Les visites sur ecolab/transport risquent d'être comptées en double.
