### ISSUE TITLE
Déplacer le proto sur un domaine demo.ecolab.ademe.fr par exemple ?

### ISSUE THREAD

**Issue by fjg** [betagouv/ecolab-transport#67]
Modifier _https://ecolab-transport.netlify.app/iframe.js_ en qqch du genre _https://demo.ecolab.ademe.fr/iframe.js_

j'ai l'impression que c'était un problème avec notre domaine netlify. Ils sont passés de netlify.com à netlify.app pour les sites hébergés chez eux. ça pose la question : est-ce qu'il faudrait pas qu'on achète un domaine ou qu'on le mette le calculateur sur quelque chose comme ecolab.ademe.fr/app/transport ?

ecolab.qqch ?
soit on rassemble tout sur ecolab.ademe.fr
soit un nouveau domaine plus court pour les applis

mais en termes de SEO on a tout intérêt à tout mettre sur ecolab.ademe.fr

(lab.eco est pas dispo)

- [ ] : passer en payant netlify (accès Jenn + CB) ?
- [ ] : avoir la main sur la zone ecolab.ademe.fr (voir avec l'équipe IT ADEME)
- [ ] : rediriger un sous-domaine choisi (ex: demo.ecolab.ademe.fr? vers netlify)
- [ ] : modifier le code pour intégrer désormais ce domaine

Après
- [ ] : recontacter les sites l'ayant intégré pour modifier le domaine

**Comment by laem** [comment]
> avoir la main sur la zone ecolab.ademe.fr (voir avec l'équipe IT ADEME)

Ah je me rendais pas compte qu'on n'avait pas la main sur les DNS, ça complique la chose

**Comment by laem** [comment]
Je vois trois solutions : 
- donner des instructions DNS à l'aveugle à l'équipe IT ADEME, ça me semble compliqué
- acheter un ecolab.x pour avoir un contrôle total sur le déploiement de nos apps. Je viens tout juste d'y penser, mais ce serait pas forcément un pb pour le SEO si on garde un lien bien visible vers ecolab.ademe.Fr dans l'iFrame. Le domaine netlify gagnerait en pagerank, mais étant donné qu'il redirige vers ecolab.ademe ce dernier y gagnerait aussi.
- ranger ecolab-transport chez Heroku et le mettre sur ecolab.ademe.fr/apps/transport ou sur un sous-domaine au choix. La perf d'Heroku sera probablement moins bonne que Netlify mais bon, ça se joue en une poignée de ms

J'explore la solution 3

**Comment by laem** [comment]
Alors, la solution 3 me semble impossible ou compliquée via heroku (il faudrait un build-pack nginx), mais possible via rails : https://github.com/axsuul/rails-reverse-proxy. A tester. 


La solution 2 est plus compliquée que prévu car tous les domaines ecolab.x ou presque sont déjà achetés ^^

**Comment by fjg** [comment]
la solution 2 est un peu risqué avec les marques et autres concurrents existants.

Tentes de voir avec les équipes IT Ademe si une délégation DNS est envisageable pour ecolab.ademe.fr. Ca serait finalement le plus simple. Avec par exemple la zone chez *alwaysdata.com* par exemple comme d'autres SE, non ?

**Comment by laem** [comment]
Suite aux discussions sur slack, je vais tenter d'adapter un truc comme ça lundi : https://github.com/ahawkin/heroku-nginx-proxy-node

**Comment by laem** [comment]
C'est en ligne sur ecolab.ademe.fr/apps/transport/
