### ISSUE TITLE
Intégration borne km par type de transport

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-transport#68]
Cf. le mail de Pierre du 14/04 (repris ci-dessous) et nos échanges, ajouter des limites min / max de km pour afficher chaque mode.
Cela permettra de figer (?) le yaml pour que l'export en CSV se fasse sur ce format et que ce soit intégré dans data.ademe.fr.

TGV   (3) | 2,4 | gCO2e/pas.km | A partir   de 150 km/aller
-- | -- | -- | --
Tramway   (1) | 3,1 | gCO2e/pas.km | Jusqu’à   12 km/aller
Métro   (1) | 3,8 | gCO2e/pas.km | Jusqu’à   20 km/aller
Vélo   assistance électrique (2) | 4,5 | gCO2e/pas.km | Jusqu’à   15 km/aller
Transilien/RER   (3) | 5,4 | gCO2e/pas.km | Jusqu’à   100 km/aller
Trains   grandes lignes (3) | 8,1 | gCO2e/pas.km | A partir   de 50 km/aller
Trottinettes   électriques (2) | 9,7 | gCO2e/pas.km | Jusqu’à   5 km/aller
Autocars   (4) | 25,6 | gCO2e/pas.km | A partir   de 15 km/aller
TER   (3) | 29,4 | gCO2e/pas.km | Jusqu’à   150 km/aller
Bus   gasoil province (4) | 103 | gCO2e/pas.km | Jusqu’à   15 km/aller
Deux   roues motorisés < 250 cm3 (4) | 61,6 | gCO2e/pas.km |  
Deux   roues motorisés > 250 cm3 (4) | 168 | gCO2e/pas.km |  
Voitures   particulières (5) | 193,2 | gCO2e/véh.km |  

Pour l’avion, Pierre propose de prendre dans le calculateur les 5 valeurs suivantes pour les 5 classes de distances (en excluant l’avion pour des distances < 500 km) :

![capture](https://user-images.githubusercontent.com/46482115/80365548-1061dc00-8888-11ea-9d6b-557b405b1990.jpg)

**Comment by laem** [comment]
Quelques remarques sur les distances : pour certains modes, ce sont des limites dures. Par exemple le métro ou le bus, à Paris dont le réseau est bien développé, le bus le plus long fait 14km. 

Pour beaucoup d'autres ce sont plutôt des limites d'usage : on garderait les 9 déciles d'usage. 

Je tique sur le TGV : la plupart des Brest-Paris passent par plusieurs villes après Rennes, qui sont toutes à moins de 150km l'une de l'autre. C'est le cas je crois sur toutes les lignes empruntées par un TGV mais pas LGV. Mais ça peut aussi être le cas en LGV, par exemple de Le Mans à Laval. Reste à mesure le nombre de personnes qui l'empruntent sur un seul arrêt, en tout cas c'est largement possible. Je mettrais plutôt une limite à 50km inclus.

Idem pour le TER dans l'autre sens : pour faire un Paris-Rennes, on a à la grosse louche une chance sur 2 de prendre un TER, or c'est 240km. 

Peut-être que c'est à ça que sert la ligne "train grande ligne", un mix de TER longue distance et de TGV courte distance. Mais je ne pense pas que cette ligne parle aux gens, TER et TGV suffisent. A moins de la renommer Intercités mais honnêtement je ne sais pas qui en France a compris ce qu'est un intercité :D 

Idem pour la trottinette électrique, le fait qu'elle soit électrique me semble justifier une limite max d'au moins 10km, et je pense aussi que beaucoup d'usages du vélo électrique font des trajets jusqu'à 30km.



--------

Je me fais aussi un peu de soucis sur le fait que plus on donne des gammes différentes aux modes, moins on peut les comparer en g/km. Mais c'est pas grave, d'autres pourront en faire un simulateur par g/km :)

**Comment by martinregner** [comment]
> Je tique sur le TGV : la plupart des Brest-Paris passent par plusieurs villes après Rennes, qui sont toutes à moins de 150km l'une de l'autre. C'est le cas je crois sur toutes les lignes empruntées par un TGV mais pas LGV. Mais ça peut aussi être le cas en LGV, par exemple de Le Mans à Laval. Reste à mesure le nombre de personnes qui l'empruntent sur un seul arrêt, en tout cas c'est largement possible. Je mettrais plutôt une limite à 50km inclus.

OK

> Idem pour le TER dans l'autre sens : pour faire un Paris-Rennes, on a à la grosse louche une chance sur 2 de prendre un TER, or c'est 240km.
 
> Peut-être que c'est à ça que sert la ligne "train grande ligne", un mix de TER longue distance et de TGV courte distance. Mais je ne pense pas que cette ligne parle aux gens, TER et TGV suffisent. A moins de la renommer Intercités mais honnêtement je ne sais pas qui en France a compris ce qu'est un intercité :D

Hihi ;) J'en prends de temps en temps, genre Bordeaux-Marseille
Je resterais bien sur les bornes proposées par Pierre : 150 km pour le TER et à partir de 50 km pour les grandes lignes à ce stade.
On ne va pas couvrir 100% des cas (des utilisateurs veulent des vélos au-délà de 100 km aussi :p)

> Idem pour la trottinette électrique, le fait qu'elle soit électrique me semble justifier une limite max d'au moins 10km, et je pense aussi que beaucoup d'usages du vélo électrique font des trajets jusqu'à 30km.

OK pour 10 et 30 km pour resp. la trotti et le VAE

> 
> Je me fais aussi un peu de soucis sur le fait que plus on donne des gammes différentes aux modes, moins on peut les comparer en g/km. Mais c'est pas grave, d'autres pourront en faire un simulateur par g/km :)

On peut encore les comparer sur les gammes où elles sont "actives" non ? :)
