### ISSUE TITLE
Réparer le CSV pour prendre en compte les bornes

### ISSUE THREAD

**Issue by laem** [betagouv/ecolab-transport#74]
Le format du YAML a changé, comme prévu.
Plus d'informations ici : https://github.com/betagouv/ecolab-transport/issues/68
Le script de génération du CSV doit être mis à jour. Il sera normalement largement simplifié 👍 

@nicolas-bonnel

**Comment by nicolas-bonnel** [comment]
Est ce que ce résultat convient ?

titre | gCO2e/km/personne | voyageurs | bornes | source | note
-- | -- | -- | -- | -- | --
avion | 683 | 0-50 sièges | 0-1000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 806 | 0-50 sièges | 1000-2000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 1200 | 0-50 sièges | 2000-3000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 453 | 50-100 sièges | 0-1000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 314 | 50-100 sièges | 1000-2000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 209 | 50-100 sièges | 2000-3000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 314 | 100-180 sièges | 0-1000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 259 | 100-180 sièges | 1000-2000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 237 | 100-180 sièges | 2000-3000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 230 | 100-180 sièges | 3000-4000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 292 | 100-180 sièges | 4000-5000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 285 | 100-180 sièges | 5000-6000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 292 | 180-250 sièges | 0-1000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 216 | 180-250 sièges | 1000-2000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 209 | 180-250 sièges | 2000-3000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 230 | 180-250 sièges | 3000-4000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 307 | 180-250 sièges | 4000-5000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 230 | 180-250 sièges | 5000-6000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 223 | 180-250 sièges | 6000-7000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 202 | 180-250 sièges | 7000-8000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 223 | 180-250 sièges | 8000-9000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 216 | 180-250 sièges | 9000-10000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 292 | 250-∞ sièges | 0-1000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 216 | 250-∞ sièges | 1000-2000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 209 | 250-∞ sièges | 2000-3000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 252 | 250-∞ sièges | 3000-4000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 259 | 250-∞ sièges | 4000-5000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 223 | 250-∞ sièges | 5000-6000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 209 | 250-∞ sièges | 6000-7000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 209 | 250-∞ sièges | 7000-8000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 230 | 250-∞ sièges | 8000-9000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 223 | 250-∞ sièges | 9000-10000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 216 | 250-∞ sièges | 10000-11000 km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
avion | 223 | 250-∞ sièges | 11000-∞ km | https://www.bilans-ges.ademe.fr/fr/basecarbone/donnees-consulter/liste-element?recherche=Avion | Par tranche de 1 000 km, la distance fait varier la taille des avions considérés et les facteurs d'émissions (pour une taille d’avion donnée, le facteur d’émission évolue par tranche de 1 000 km) ; Base Carbone ADEME.
TGV | 2.4 | 1 | à partir de 150km | http://medias.sncf.com/sncfcom/pdf/co2/Information_CO2_des_prestations_de_transport_Methodologie_generale.pdf | 2,4 gCO2e/km/personne ; SNCF 2018
Intercités | 8.1 | 1 | à partir de 50km | http://medias.sncf.com/sncfcom/pdf/co2/Information_CO2_des_prestations_de_transport_Methodologie_generale.pdf | 8,1 gCO2e/km/personne ; SNCF 2018
voiture thermique |   | 1 |   |   | 193,2 gCO2e/km/véhicule ; calculs ADEME, base Comptes des transports CGDD (2019), moyenne nationale toutes distances, toutes carburations
autocar | 25.6 | 1 | à partir de 15km |   | 25,6 gCO2e/km/personne ; calculs ADEME à partir d'HBEFA (2020)
marche | 0 | 1 | jusqu'à 10km |   | 0 gCO2e/km/personne ; l'impact de la marche est ici considéré comme négligeable
vélo | 0 | 1 | jusqu'à 30km |   | 0 gCO2e/km/personne ; l'impact du vélo est ici considéré comme négligeable
vélo à assistance électrique | 4.5 | 1 | jusqu'à 30km |   | 4,5 gCO2e/km/personne pour la phase d'usage ; Etude ADEME, Modélisation et évaluation environnementale de produits de consommation et biens d’Équipement, en cours de publication
trottinette électrique | 9.7 | 1 | jusqu'à 10km |   | 9,7 gCO2e/km/personne pour la phase d'usage ; Etude ADEME, Modélisation et évaluation environnementale de produits de consommation et biens d’Équipement, en cours de publication
bus thermique - 0-150 k habitants | 103 |   | jusqu'à 15km |   | 103 gCO2e/km/personne ; calculs ADEME à partir d'HBEFA (2020)
bus thermique - 150-250 k habitants | 103 |   | jusqu'à 15km |   | 103 gCO2e/km/personne ; calculs ADEME à partir d'HBEFA (2020)
bus thermique - 250-∞ k habitants | 103 |   | jusqu'à 15km |   | 103 gCO2e/km/personne ; calculs ADEME à partir d'HBEFA (2020)
tramway | 3.1 | 1 | jusqu'à 12km | https://www.ratp.fr/index.php/question/pourquoi-calculer-les-emissions-de-gaz-a-effet-de-serre-dues-a-ses-deplacements | 3,1 gCO2e/km/personne ; RATP 2020
métro | 3.8 | 1 | jusqu'à 20km | https://www.ratp.fr/index.php/question/pourquoi-calculer-les-emissions-de-gaz-a-effet-de-serre-dues-a-ses-deplacements | 3.8 gCO2e/km/personne ; RATP 2020
scooter et moto légère | 61.6 | 1 | jusqu'à 150km |   | Deux roues thermiques < 250cm3 
moto | 168 | 1 |   |   | Deux roues thermiques > 250cm3 ; 168 gCO2e/km/personne
RER ou Transilien | 5.4 | 1 | jusqu'à 100km | http://medias.sncf.com/sncfcom/pdf/co2/Information_CO2_des_prestations_de_transport_Methodologie_generale.pdf | 5,4 gCO2e/km/personne ; SNCF 2018
TER - moyenne | 29.4 |   | jusqu'à 150km | http://medias.sncf.com/sncfcom/pdf/co2/Information_CO2_des_prestations_de_transport_Methodologie_generale.pdf | Moyenne : 29,4 gCO2e/km/personne ; SNCF 2018
TER - électricité | 8.91 |   | jusqu'à 150km | http://medias.sncf.com/sncfcom/pdf/co2/Information_CO2_des_prestations_de_transport_Methodologie_generale.pdf | Moyenne : 29,4 gCO2e/km/personne ; SNCF 2018
TER - diesel | 79.8 |   | jusqu'à 150km | http://medias.sncf.com/sncfcom/pdf/co2/Information_CO2_des_prestations_de_transport_Methodologie_generale.pdf | Moyenne : 29,4 gCO2e/km/personne ; SNCF 2018

**Comment by laem** [comment]
Ah oui tiens, on aurait pu intégrer les variations kilométriques de l'avion dans l'attribut bornes.
Mais oui c'est 👍 
D'ailleurs quand la nouvelle version de la base GES sortira, on fera probablement évoluer le champs avion.

**Comment by laem** [comment]
@nicolas-bonnel nous avons comme prévu fait évoluer le schéma de l'avion, d'où la nouvelle version majeure du code. Voir #86

**Comment by nicolas-bonnel** [comment]
@laem : Je voulais m'occuper de ca un peu plus tôt, mais on a été très pris avec la publication des DPE. La pull request est envoyée.

**Comment by laem** [comment]
Pas de souci :)
