### ISSUE TITLE
Distinguer les FE des avions avec et sans trainée

### ISSUE THREAD

**Issue by martinregner** [betagouv/ecolab-transport#87]
La nouvelle Base Carbone distingue 2 FE pour l'aviation : **AVEC et SANS l'impact induit des trainées de condensation**

Modifier la barre avion pour : 
- différencier SANS (même couleur que les autres barres) et AVEC (couleur + claire et/ou dégradé vers une extrémité de barre transparente)
- garder dans la hiérarchisation l'intégralité de la barre (valeur AVEC)
- ajouter des explications sur cette distinction : selon où on clique sur la barre ? lien dans la source vers une section dédiée du gitbook ?

**Comment by laem** [comment]
Fait dans #86
